# Netlify configuration for static deployment
# Note: This build uses Cloudflare Workers format which is not compatible with Netlify
# For Netlify deployment, use the netlify-deploy folder with pre-built files
# Or deploy via Cloudflare Pages for full functionality

[build]
  # Skip build - use pre-built dist folder
  command = "echo 'Using pre-built files from dist/'"
  publish = "dist"
  base = ""

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Note: Cloudflare Workers (_worker.js) won't run on Netlify
# The app needs to be rebuilt for traditional static hosting
# Recommendation: Use Cloudflare Pages for full functionality
